## Сортировка данных: ORDER BY

Запросим список картин, выпущенных после 1980 года:

```sql
SELECT title,
       release_year
FROM video_products
WHERE release_year > 1980;
```

```bash
('Кто подставил кролика Роджера', 1988)
('Последний киногерой', 1993)
('Она написала убийство', 1984)
('Лас-Вегас', 2003)
('Паркер Льюис не проигрывает', 1990)
('Койот против Acme', 2023)
```
Данные получены, но даты идут вразнобой. Надо бы отсортировать выборку по дате выхода картины в свет. 

Для сортировки результатов запроса в SQL есть ключевое слово `ORDER BY`. Обратите внимание: `ORDER BY` пишется после условия `WHERE`. Это логично — сначала выбираем данные и после этого выстраиваем их по порядку. 

```sql
SELECT title,
       release_year
FROM video_products
WHERE release_year > 1980
ORDER BY release_year;
```

```bash
('Она написала убийство', 1984)
('Кто подставил кролика Роджера', 1988)
('Паркер Льюис не проигрывает', 1990)
('Последний киногерой', 1993)
('Лас-Вегас', 2003)
('Койот против Acme', 2023)
```

***
## Направление сортировки

По умолчанию команда `ORDER BY` выполняет сортировку по возрастанию. Чтобы явным образом задать направление сортировки, после имени столбца указывается ключевое слово `ASC` (по возрастанию) или `DESC` (по убыванию). 

Отсортировать фильмы в порядке «от новых к старым» можно так:

```sql
...

ORDER BY release_year DESC;
```

Результирующую выборку можно отсортировать и по текстовым полям, тогда результаты будут выведены в алфавитном порядке. Сортировка с ключевым словом DESC «развернёт» порядок, и записи будут выведены в порядке от Я до А. 

При сортировке можно указать несколько полей, перечислив их через запятую. Результаты отсортируются по первому полю, а при равных значениях первого поля — по второму. 

Отсортируем выборку по полю `product_type` в обратном порядке (от Я к А), а фильмы с одинаковым типом отсортируем по алфавиту:

```sql
SELECT product_type,
       title
FROM video_products
WHERE release_year > 1980
ORDER BY product_type DESC, title;
```

Сначала записи отсортируются по типу картины в обратном алфавитном порядке (от Я к А); фильмы одинакового типа будут отсортированы по названиям — по алфавиту.

```bash
('Фильм', 'Койот против Acme')
('Фильм', 'Кто подставил кролика Роджера')
('Фильм', 'Последний киногерой')
('Сериал', 'Лас-Вегас')
('Сериал', 'Она написала убийство')
('Сериал', 'Паркер Льюис не проигрывает')
```

***
## Ограничение и сдвиг выборки: LIMIT и OFFSET

В ответ на запрос может вернуться большая выборка; но зачастую нужно получить лишь несколько записей из неё. Примером может служить постраничное отображение информации на сайте.

Допустим, на каждую страницу сайта нужно вывести по два фильма из базы данных. Значит, при запросе нужно получить только две записи из БД, а не полный набор записей.

Для ограничения количества строк, возвращаемых в ответ на SQL-запрос, применяют ключевое слово `LIMIT` (англ. «ограничение») и `OFFSET` (англ. «смещение»). 

```sql
LIMIT <сколько строк нужно показать> OFFSET <на сколько строк сдвинуть выборку>;
```

Отсортируем записи по алфавиту и ограничим количество возвращаемых записей:

```sql
SELECT product_type,
       title
FROM video_products
ORDER BY title
LIMIT 2;
```

```py
('Мультсериал', 'Безумные мелодии Луни Тюнз')
('Мультсериал', 'Весёлые мелодии')
```

При постраничном размещении информации эти две записи можно выкладывать на первую страницу. На вторую страницу нужно вывести третью и четвёртую записи.

Если нужно вернуть определённое число записей, но начинать нужно не с первой записи в выборке — после `LIMIT` ставят оператор `OFFSET` и в нём указывают, сколько записей нужно пропустить.

Вернём две записи из нашей выборки, но две первые пропустим:

```sql
SELECT product_type,
       title
FROM video_products
ORDER BY title
LIMIT 2 OFFSET 2;
```

В результате вернулись третья и четвёртая записи из отсортированного списка 
фильмов:

```py
('Фильм', 'Койот против Acme')
('Фильм', 'Кто подставил кролика Роджера')
```

В переводе с SQL на русский: 

* возьми значения полей `product_type` и `title` всех записей таблицы **video_products**,

* отсортируй результаты по полю `title` в алфавитном порядке,

* покажи две строки, но пропусти две и начни с третьей.

Применение `LIMIT` и `OFFSET` без явной сортировки `ORDER BY` не вызовет ошибки, но может привести к непредсказуемым результатам: заранее неизвестно, в каком порядке размещены записи в БД. Ограничивать выборку надо после сортировки.

Порядок ключевых слов важен: сортировать значения и ограничивать выборку нужно лишь после того, как будут указаны таблицы и столбцы, которые должны попасть в выборку.

В SQL-запросах, которые вы пишете, порядок инструкций должен быть таким:

* SELECT

* FROM

* WHERE (опционально)

* ORDER BY

* LIMIT OFFSET

In [ ]:
import sqlite3

con = sqlite3.connect('db.sqlite')
cur = con.cursor()

# Напишите SQL запрос в строке.
results = cur.execute('''
SELECT title,
       description
FROM ice_cream
WHERE is_published = 1
ORDER BY title DESC
LIMIT 2 OFFSET 1;
''')


for result in results:
    print(result)

con.close()